### PR TITLE
Add new Horizon endpoints and fields

### LINKED ISSUE #57: Update SDK with new /trades endpoint

### LINKED ISSUE #58: Update SDK with new /trade_aggregations endpoint

### LINKED ISSUE #59: Update SDK with new all assets endpoint

### PR DESCRIPTION
**Pull request by bartekn**
Endpoints:
* `/assets` - close #59 
* `/trade_aggregations` - close #58 
* `/trades` - close #57 

Fields:
* `transaction_hash` on Operation,
* `created_at` on Operation,
* `base_fee_in_stroops` and `base_reserve_in_stroops` on Ledger.

### CODE REVIEW

**Comment by bnogalm** [comment]
TradesPageDeserializerTest.java is using test link data with old path. And test checks old path.

**Comment by bartekn** [comment]
> TradesPageDeserializerTest.java is using test link data with old path. And test checks old path.

Path didn't change.

**Comment by bnogalm** [comment]
Just to be sure:
https://github.com/stellar/java-stellar-sdk/pull/71/files#diff-dc4eb474675b7b107c1f1ccd99e87b49
-        super(serverURI, "order_book/trades");
+        super(serverURI, "trades");

https://github.com/stellar/java-stellar-sdk/pull/71/files#diff-283b5933ee8e3d1206e40308cf4eb032
-        assertEquals("https://horizon-testnet.stellar.org/order_book/trades?" 
+        assertEquals("https://horizon-testnet.stellar.org/trades?" 


But:
https://github.com/stellar/java-stellar-sdk/blob/8a5602c2702a0ce37439fa5cb7d32bc62ed83171/src/test/java/org/stellar/sdk/responses/TradesPageDeserializerTest.java

Links  point to order_book/trades
Either test is not updated or path changed accidentally from "order_book/trades" to "trades", or i need to sleep a bit.

**Comment by bartekn** [comment]
@bnogalm yeah, you're correct, I just changed the fields within trade records that changed but I didn't change any other field (including links). Fixed.

**Pull request merged**
