### PR TITLE
define `cursor`, `order` and `limit` in AssetsRequestBuilder object.

### LINKED ISSUE #371: Feature Request: define order and limit in AssetsRequestBuilder object
### What problem does your feature solve?
When retrieving the list of assets it is not possible to se the `order` and `limit` in the **AssetsRequestBuilder** object which is used to perform the `Asset List` request. Developers must create instead a **RequestBuilder** to be able to pass these parameters

### What would you like to see?
Add `order(Order order)` and `limit(int number)` methods in the AssetsRequestBuilder

### What alternatives are there?
Developers can create and configure a RequestBuilder instead of working with  AssetsRequestBuilder abstraction

### PR DESCRIPTION
**Pull request by overcat**
fix #371 

Sorry for creating another PR like this, please see details at https://github.com/stellar/java-stellar-sdk/pull/519#issuecomment-1707412963

Let's ignore the CI failure caused by some unformatted code. We have resolved this issue in #521.

### CODE REVIEW

**Comment by sreuland** [comment]
can you add the new test case from the original pr #519 as well:

https://github.com/stellar/java-stellar-sdk/pull/519#discussion_r1315322660

**Comment by overcat** [comment]
> can you add the new test case from the original pr #519 as well:
> 
> [#519 (comment)](https://github.com/stellar/java-stellar-sdk/pull/519#discussion_r1315322660)

There is already a relevant test in the original code, in the previous PR, I also kept this unchanged here.
https://github.com/stellar/java-stellar-sdk/blob/d9d0058ae4cb0adc20dc0a1e04e56bb2f7ec321d/src/test/java/org/stellar/sdk/requests/AssetsRequestBuilderTest.java#L11-L25

**Comment by sreuland** [comment]
> There is already a relevant test in the original code, in the previous PR, I also kept this unchanged here.

ah, I see, this is because java has no `receiver` or `self` type available from abstract class methods, so, have to implement same methods on each concrete sub-class.

**Review by sreuland — APPROVED** [review]

**Comment by sreuland** [comment]
@overcat , I was going to merge, but it looks like this is stuck waiting on circleci status, not sure when it clears up. it will be great once the soroban branch merges in with the[ fix to migrate off circleci to gh actions](https://github.com/stellar/java-stellar-sdk/pull/512)

**Comment by overcat** [comment]
> @overcat , I was going to merge, but it looks like this is stuck waiting on circleci status, not sure when it clears up. it will be great once the soroban branch merges in with the[ fix to migrate off circleci to gh actions](https://github.com/stellar/java-stellar-sdk/pull/512)

So let's first merge #521, but don't release it. Wait until we merge this PR and then release it together. This way I can try to fix the CI.

**Comment by sreuland** [comment]
> So let's first merge https://github.com/stellar/java-stellar-sdk/pull/521, but don't release it. Wait until we merge this PR and then release it together. This way I can try to re-trigger the CI.

@overcat, #521 has been merged, if you make a no-op commit onto this pr maybe it will release/reset the gha, and re-run again?

**Comment by overcat** [comment]
> > So let's first merge #521, but don't release it. Wait until we merge this PR and then release it together. This way I can try to re-trigger the CI.
> 
> @overcat, #521 has been merged, if you make a no-op commit onto this pr maybe it will release/reset the gha, and re-run again?

It turns green now.

**Pull request merged**
