### PR TITLE
Soroban to mainline, 0.41.0 release prep

### PR DESCRIPTION
**Pull request by sreuland**
Merging the Soroban sdk support feature branch back into master.

This has gone through reviews already, only updated file in here is [CHANGELOG.md](https://github.com/stellar/java-stellar-sdk/pull/532/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)

### CODE REVIEW

**Comment by sreuland** [comment]
@overcat , thanks for getting #534 merged in, any other pr's that need to come in? you mentioned an issue related to operations effects that may have a fix pending? Beyond that, this PR should then be ready to merge soroban back to master and issue next mainline release including soroban support as `0.41.0`.

**Comment by overcat** [comment]
> @overcat , thanks for getting #534 merged in, any other pr's that need to come in, such as #528 correct? you mentioned an issue related to operations effects that may have a fix needed also? Once finalized there, this PR should then be ready to merge soroban back to master and issue next mainline release including soroban support as `0.41.0`.

We should include #535 and #528.

Should the next version be `0.41.0` or `0.41.0-beta4`? I noticed that other software like horizon, rs-soroban-sdk, etc., have not yet released a stable version, so I think it should be `0.41.0-beta4`? Is that correct?

**Comment by sreuland** [comment]
> Should the next version be `0.41.0` or `0.41.0-beta4`? I noticed that other software like horizon, rs-soroban-sdk, etc., have not yet released a stable version, so I think it should be `0.41.0-beta4`? Is that correct?

I heard some feedback that `0.41.0` was anticipated as next semver release since it would likely be the release to use with soroban on testnet, which will be upgrading to soroban/protcol 20 soon. Some other releases have started similar, horizon came out with 2.27.0 which has soroban, and some of the go sdks were released with soroban support like https://github.com/stellar/go/releases/tag/horizonclient-v12.0.0

**Comment by overcat** [comment]
> > Should the next version be `0.41.0` or `0.41.0-beta4`? I noticed that other software like horizon, rs-soroban-sdk, etc., have not yet released a stable version, so I think it should be `0.41.0-beta4`? Is that correct?
> 
> I heard some feedback that `0.41.0` was anticipated as next semver release since it would likely be the release to use with soroban on testnet, which will be upgrading to soroban/protcol 20 soon. Some other releases have started similar, horizon came out with 2.27.0 which has soroban, and some of the go sdks were released with soroban support like https://github.com/stellar/go/releases/tag/horizonclient-v12.0.0

Okay, then let's set the version to `0.41.0`.

**Review by JakeUrban — APPROVED** [review]

**Pull request merged**
