### PR TITLE
shade all dependencies to avoid conflicts

### PR DESCRIPTION
**Pull request by jillesvangurp**
Addresses #122

We cannot use the original jar because of Spring Boot autoconfiguring included things, which then fails because they are old versions. Gson and javax.validation are the two problematic dependencies. 

There are several other things in the dependencies that I'd prefer to not have there like jersey and mockito (why is this a compile dependency).

Shading takes care of removing the conflicts for us; so I simply shaded everything. 

I've signed the contributor agreement.

### CODE REVIEW

**Comment by jillesvangurp** [comment]
Travis currently breaks because of an out dated gradle. This will require merging of #119 to upgrade gradle. I used gradle 4.9 and it builds fine with that.

**Comment by bartekn** [comment]
#119 is merged. Can you rebase `master`?

**Comment by jillesvangurp** [comment]
@bartekn just updated my branch

**Comment by cyberluke** [comment]
How does the shading work for you? I download current SDK 0.3.3 and have this exact same issue again: https://github.com/stellar/java-stellar-sdk/issues/122

**Comment by jillesvangurp** [comment]
@cyberluke We merged but never released a fix for this.  

We have another fix in the works that removes jersey entirely. @bartekn we could actually get rid of this shading if we merge that ( #147 )

@cyberluke, give my fork a spin  by depending on: 'com.github.Inbot:java-stellar-sdk:v0.3.2.1-inbot-get-rid-of-jersey'

**Comment by cyberluke** [comment]
@jillesvangurp I just forked and sent pull request that solves all my issues. The main fuck up was because of using guava android, not guava jre: https://github.com/stellar/java-stellar-sdk/pull/152

**Comment by jillesvangurp** [comment]
Try my fork, it shades properly. I use this with spring boot 2.x.

**Pull request merged**
