### PR TITLE
0.7.0

### PR DESCRIPTION
**Pull request by bartekn**
To be included:
- [x] #206
- [x] #205

### CODE REVIEW

**Comment by overcat** [comment]
Can we include #200 and #201 in 0.7.0?

**Comment by bartekn** [comment]
#201 is good. For #200 I think we need a different fix (if I understand correctly there's no paging token for order book response?). Silencing exceptions is generally bad idea.

**Comment by overcat** [comment]
Hi @bartekn, there's no paging token for order book response, so we get `UnsupportedOperationException` from [here](https://github.com/stellar/java-stellar-sdk/blob/98da7754299320a777bbad2485c69911c13dc99f/src/main/java/org/stellar/sdk/responses/Response.java#L34), can you show me how to fix it gracefully?

**Comment by bartekn** [comment]
@overcat added a PR fixing this with a different approach here: #206.

**Pull request merged**
