### PR TITLE
Fix missing  in AccountResponse class.

### LINKED ISSUE #442: `AccountResponse.flags` is missing `.getClawbackEnabled()`
`AccountRepsonse.flags` is supposed to provide access to the JSON values returned from horizon, but it is missing one, the `auth_clawback_enabled` flag. 

Looks like we missed this when we added general support for clawbacks.

### PR DESCRIPTION
**Pull request by lijamie98**
Closes #442 

Fix missing  `auth_clawback_enabled` filed  in AccountResponse class.

### CODE REVIEW

**Review by JakeUrban — APPROVED** [review]
Thanks Jamie!

**Comment by JakeUrban** [comment]
Can we publish a release once this is merged?

**Review by tamirms — APPROVED** [review]

**Comment by lijamie98** [comment]
> Can we publish a release once this is merged?

Sure! 0.37.0 is now published. https://github.com/stellar/java-stellar-sdk/releases

**Comment by secondclaw** [comment]
Should this fix have also included missing clawback flag in AccountResponce.Balance[] ?
Balance objects have data on other flags set in each established trust line, but not the clawback flag.

**Comment by JakeUrban** [comment]
What attribute do you believe is missing from `AccountResponse.Balance` @secondclaw? 

A JSON balance object returned from Horizon looks like this:

```json
{
      "balance": "516059.6800000",
      "limit": "922337203685.4775807",
      "buying_liabilities": "0.0000000",
      "selling_liabilities": "0.0000000",
      "last_modified_ledger": 1055965,
      "is_authorized": true,
      "is_authorized_to_maintain_liabilities": true,
      "asset_type": "credit_alphanum4",
      "asset_code": "SRT",
      "asset_issuer": "GCDNJUBQSX7AJWLJACMJ7I4BC3Z47BQUTMHEICZLE6MU4KQBRYG5JY6B"
}
```

I don't see anything that pertains to clawbacks here. Let me know if I'm missing something though.

**Comment by secondclaw** [comment]
"balances": [ { "balance": "0.0000000", "limit": "922337203685.4775807", "buying_liabilities": "0.0000000", "selling_liabilities": "0.0000000", "last_modified_ledger": 1004162, "is_authorized": true, "is_authorized_to_maintain_liabilities": true, "is_clawback_enabled": true, "asset_type": "credit_alphanum12", "asset_code": "PEND1", "asset_issuer": "GCQHCSY4SWXDRJ7E73CZH3XCMK6CKTS35WOWTYZSWSDAIS3WHT4KL5SB" },


It apparently only shows up if clawback is enabled on trust line.

**Comment by JakeUrban** [comment]
Ok, thanks for pointing this out. It looks like our documentation is missing this attribute (and others) as well. I'll file an new issue here to add the attribute to `Balance`.

**Comment by secondclaw** [comment]
Is_clawback_enabled

If an account has established a trust line that has clawback enabled, and I 
look at that account in Stellar Lab, I can see the flag inside Balances array .
But it's not exposed in java SDK.

See account GA27VME5Z4AGZSAWQU3N45JUQJJPASBBBSLTFCASV7DXUMVTEJX2QD64

**Pull request merged**
