### PR TITLE
Protocol 19 - CAP-40 Signed Payload Signer

### LINKED ISSUE #410: Update StrKey implementation to support CAP-40 signed payloads
Java-specific issue for the parent, stellar/go#4262.

### LINKED ISSUE #412: Update API definitions to conform to Protocol 19

### PR DESCRIPTION
**Pull request by sreuland**
have reviewed these changes for CAP-40 Signed Payload Signer on [PR #413](https://github.com/stellar/java-stellar-sdk/pull/413). renamed source repo branch to 'protocol-19', triggered [413](https://github.com/stellar/java-stellar-sdk/pull/413) to close, opened this PR on new branch name.

> Update the Java SDK to have the new XDR schema for [Protocol 19](https://github.com/stellar/go/tree/horizon-protocol-19)
>
> this change focuses on supporting  [CAP-40](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0040.md#xdr-changes) , namely the new Signed Payload Signer as new StrKey.
>
>Update the StrKey encoding/decoding to include the new Signed Payload Signer, add more tests where signed payload signer could appear such as SetOptionsOperation and AccountEntry.

Closes #412 
Closes #410 

>can ignore all changed files in `src/main/java/org/stellar/sdk/xdr`, they are generated code from `xdrgen` tool against the latest xdr schema files.

>This is first half of Protocol 19 support, a follow-on PR will be coming for remaining Protocol 19 support of [CAP-21](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0021.md) which introduces new tx pre-conditions on of which is `extraSigners` which this new Signed Payload Signer can be used.

### CODE REVIEW

**Review by leighmcculloch — COMMENTED** [review]
❓ Did we, or are we, adding a function for signing a payload and generating a decorated signature to attach to a transaction? I couldn't see that functionality in this PR.

**Comment by sreuland** [comment]
> ❓ Did we, or are we, adding a function for signing a payload and generating a decorated signature to attach to a transaction? I couldn't see that functionality in this PR.

Ok, have not done that aspect, just have the StrKey encode/decode updated for payload signer. Is that signature generation in the go client sdk for reference? I can get that in here. The encoded payload signer should go right into the Precondtions.ExtraSigners correct? And then I think need to add a AbstractTransaction.sign(SignedPayloadSigner signedPayloadSigner) to encapsulate both generation and adding the signedpayload decorated sig to the tx in one.

**Comment by leighmcculloch** [comment]
The signing operation should be independent of a transaction, then let people add the signature manually. That's how the Go SDK works anyway.

https://github.com/stellar/go/blob/horizon-protocol-19/keypair/full.go#L115-L123
https://github.com/stellar/go/blob/master/txnbuild/transaction.go#L332-L341

**Comment by sreuland** [comment]
> The signing operation should be independent of a transaction, then let people add the signature manually. That's how the Go SDK works anyway.

@leighmcculloch , thanks for the references, I added similar convention into Java SDK, [ up for review on PR #415](https://github.com/stellar/java-stellar-sdk/pull/417)

**Pull request merged**
