### PR TITLE
Remove the dependency on Guava.

### PR DESCRIPTION
**Pull request by overcat**
Part of #496 

This PR does not include XDR changes, I need to wait for the merge of https://github.com/stellar/xdrgen/pull/168 before initiating a separate XDR-related PR.

----
This PR is almost completed, but before merging it, we need to merge #525 and #527 first and remove `com.google.guava:guava:32.1.2-android` in build.gradle.

### CODE REVIEW

**Comment by overcat** [comment]
Currently, Java 8 does not have built-in support for Base16 and Base32. Are you inclined to introduce the [Apache Commons Codec](https://commons.apache.org/proper/commons-codec/) package or implement it ourselves in the SDK?

**Comment by overcat** [comment]
This PR is almost completed. After checking it again tomorrow, I will request a review :-)

**Comment by overcat** [comment]
commons-codec looks relatively simple and doesn't have a series of dependencies like Guava, so I think it would be great to introduce it, right?

**Comment by overcat** [comment]
Hi @sreuland, this PR is ready for review, it's big PR 😂

**Comment by sreuland** [comment]
@overcat , #530 was merged into `soroban`, looks like need to port latest `soroban` back to here to finalize.

**Comment by overcat** [comment]
> @overcat , #530 was merged into `soroban`, looks like need to port latest `soroban` back to here to finalize. I updated pr with port from latest on `soroban` - [6c28a2e](https://github.com/stellar/java-stellar-sdk/commit/6c28a2ed74c46b62db83c83d256b31458ac1cca2), tests passing afterwards, looks ready to merge.

Great, thanks @sreuland.

**Comment by overcat** [comment]
Hi @sreuland, It seems that the conflict has not been resolved correctly. Please check https://github.com/stellar/java-stellar-sdk/pull/524/files#diff-04e963815abf17aa3afc8545dd7431ba59aa861e57e3a04f53c5c33b82482305L12

Do you mind if I revert this PR and then create a new PR to merge into the soroban branch, and finally squash these three commits on the soroban branch?

**Comment by overcat** [comment]
I have already fixed this issue in the soroban branch and pushed the code after squashing by using `git push origin soroban --force-with-lease`

**Comment by sreuland** [comment]
ok, I had done manual merge of conflicts in SimulateTransactionResponse and SorabanServerTest after porting soroban and looks like chose incorrect direction, thanks for resolving.

**Pull request merged**
