### PR TITLE
Add tests to verify if the SDK can be successfully integrated into an Android project.

### LINKED ISSUE #458: Add unit test coverage to verify android sdk version support
### What problem does your feature solve?
verify min android sdk versions work with packaged/shadowed jar distributable.

### What would you like to see?
a unit test that can run the android emulator for a given android sdk version, such as 28, with a sample apk project like Basic Activity template from the android studio - https://github.com/stellar/java-stellar-sdk/issues/450#issuecomment-1248152732

### PR DESCRIPTION
**Pull request by overcat**
Closes #458

We have created an Android project that includes a simple invocation of the Stellar SDK. Afterwards, we run this app on the emulator to see if the app can function properly.
Screenshot_20230822_170241

### CODE REVIEW

**Comment by sreuland** [comment]
want to mention https://github.com/stellar/java-stellar-sdk/issues/450 for additional background context on android

android usage raises more reason to consider okhttp alternatives since okhttp has kotlin deps that can conflict with kotlin in android runtimes.

**Comment by overcat** [comment]
The current dependencies used by the SDK have not been upgraded for a long time. This PR also helps us confirm that upgrading the dependencies will not cause disruptions.

**Comment by sreuland** [comment]
> The current dependencies used by the SDK have not been upgraded for a long time. This PR also helps us confirm that upgrading the dependencies will not cause disruptions.

yes, sound good for interim, the dependency modernization has been allocated to https://github.com/stellar/java-stellar-sdk/issues/496

**Comment by overcat** [comment]
Hi @sreuland, is there anything that needs to be changed in this PR, and if not, can we merge it?

**Comment by overcat** [comment]
Hi @sreuland, is there anything that needs to be changed in this PR, and if not, can we merge it?

**Review by sreuland — APPROVED** [review]
looks good!

**Pull request merged**
